- template.yaml
In order to connect to Neptune, it appears that this is necessary:
- Add policy for VPC connection
> Add vpc-policy for ENI connection

- template.yaml
To avoid unnecessary invocations, adjusted event pattern to only match events from folders _nvi-candidates_ and _resources_
> PersistedResourcesEventRule: Only match relevant folders

- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/EventType.java
- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/PersistedResourceEvent.java
- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoader.java
- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoaderTest.java
- template.yaml
Jira task: [Distinguish between new, updates (potentially) and deletions](https://unit.atlassian.net/browse/NP-45931)
Not able to distinguish between new/create and update for s3 events, see links:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/EventBridge.html
[AWS Lambda using S3 Trigger: Distinguish between create and update](https://stackoverflow.com/questions/50866658/aws-lambda-using-s3-trigger-distinguish-between-create-and-update)
Discussed this with @brinxmat, we can handle this by doing a sparql ASK before inserts/updates.
> Np 45931 distinguish update types

- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoaderTest.java
- data-report-commons/src/main/java/commons/db/GraphStoreProtocolConnection.java
- data-report-commons/src/test/java/commons/db/GraphStoreProtocolConnectionTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchDataReportTest.java
- template.yaml
Looking at [the documentation](https://docs.aws.amazon.com/neptune/latest/userguide/feature-overview-endpoints.html#feature-overview-cluster-endpoints), we are not doing things in the right way.
- Use NeptuneCluster.Endpoint rather than attempting to split out read operations.
> Use endpoint for read/write

- bulk-load/build.gradle
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/Nquads.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/NquadsTest.java
- settings.gradle
- First step to create nquads to be loaded via AWS Neptune's bulk load functionality
- Convert a file containing triples to a set of nquads where the graph name includes the file name
> Add triple-to-nquad conversion

- data-loading/src/main/resources/nvi_context.jsonld
- report-api/src/main/resources/template/nvi.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/TestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/ApprovalGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/CandidateGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/NviOrganizationGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/publication/OrganizationGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestApproval.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviCandidate.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviOrganization.java
- Modified nvi sparql to provide the remaining headers `institutionId`, `institutionPoints` and `institutionApprovalStatus` to the nvi endpoint based on nvi approval data
> Np 46085 nvi endpoint, remaining headers

- bulk-load/build.gradle
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/loader/BulkLoadHandler.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/loader/ErrorLogRequest.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/loader/Format.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/loader/LoaderSpec.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/loader/Parallelism.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/loader/BulkLoadHandlerTest.java
- template.yaml
- Speculative template as I'm not sure exactly how to do things (we'll need to deploy in Sandbox to test)
- Adds a lambda that can be initiated to send a request to Neptune's /loader endpoint to read all NQuads files from a bucket and load these in bulk
- Since Neptune doesn't produce logs in the traditional sense, you need to query the loader endpoint with the loadId of the load request. I have implemented this functionality in this lambda since it is something that you should only need to do based on the request emitted by initiating this lambda. It could have been another lambda, but I don't see a huge value in creating more code right now. We may choose to split this code out later.
> Add bulk loader

- database-tools/build.gradle
- database-tools/src/main/java/no/sikt/nva/data/report/dbtools/DatabaseResetHandler.java
- database-tools/src/main/java/no/sikt/nva/data/report/dbtools/ResetAction.java
- database-tools/src/main/java/no/sikt/nva/data/report/dbtools/model/TokenResponse.java
- database-tools/src/test/java/no/sikt/nva/data/report/dbtools/DatabaseResetHandlerTest.java
After successful `initializeDatabaseReset` action, use provided token to request `performDatabaseReset` action.
Docs: https://aws.amazon.com/blogs/database/resetting-your-graph-data-in-amazon-neptune-in-seconds/
> Perform database reset

- template.yaml
Deployment failed due to `key-batches-{AccountId} already exists in stack`. Renamed to` data-report-key-batches`
> Rename KeyBatchesBucketName to "data-report-key-batches"

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/GenerateKeyBatchesHandler.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/transformer/GenerateKeyBatchesHandlerTest.java
- Log location 
- Make test `shouldReadGenerateBatchesFromS3LocationProvidedInEventBody` more specific
> Log location in GenerateKeyBatchesHandler

- report-api/src/main/resources/template/nvi.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/TestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/CandidateGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviCandidate.java
Added following fields to data returned from nvi endpoint:
- `globalApprovalStatus`
- `reportedPeriod`
- `totalPoints`
- `publicationTypeChannelLevelPoints`
- `authorShareCount`
- `internationalCollaborationFactor`
`reportedPeriod` is optional, only relevant for reported nvi candidates
> Np 46247 Supply more nvi data, globalApprovalStatus and more

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandler.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/MissingIdException.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/Nquads.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandlerTest.java
- If the id node is missing from JSON, the graph name will be "null", this is an error
- It is unlikely that this will ever occur, but it is a valid case that is an error
> Catch missing graph name

- report-api/src/main/resources/template/nvi.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/ValidRequestSource.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/HeaderConstants.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/TestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviCandidate.java
New field added to data supplied from nvi endoint: `pointsForAffiliation`
Count number of affiliations for institutions and divide `institutionPoints` on `numberOfAffiliationsForInstitution` to present `pointsForAffiliation` in result.
> Np 46278 Points for affiliation

- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/formatter/ExcelFormatter.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/xlsx/Excel.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchDataReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/formatter/ExpectedExcelFormatter.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/ExcelAsserter.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/ExcelComparer.java
- Implement `ExcelFormatter`, use `ResultSet` to populate excel workbook
- Added `ExcelAsserter` to assert expected results in test `shouldReturnDataInExcelSheetWhenContentTypeIsExcel`, this does not care about the order of the data rows.
> Np 46190 Implement ExcelFormatter, actually deliver query result in Excel file

- docs/openapi.yaml
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReport.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchDataReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/LocalFusekiTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/BadRequestProvider.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/ValidExcelRequestSource.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/ValidRequestSource.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/requests/FetchDataReportRequest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/requests/FetchNviInstitutionReportRequest.java
- template.yaml
First part of moving nvi institution report to its own handler.
- Added `FetchNviInstitutionReport` which does noting atm. Supports media types for csv and excel.
Some refactoring in tests:
- Renamed `TestingRequest` to `FetchDataReportRequest`
- Added `FetchNviInstitutionReportRequest`
- Created `LocalFusekiTest` for setting up local fuseki servers i both test classes
> Np 45429 fetch nvi institution report handler

- report-api/build.gradle
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReport.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/requests/FetchNviInstitutionReportRequest.java
- Take in `reportingYear` as path parameter, this allows reporting handler be "agnostic" to which period is open etc (nvi logic). It also supports possibility of multiple open periods which one can fetch an institution report for.
- For now, just logging `reportingYear` and requesting users `topLevelCristinOrg`, these will be used in the sparql query for the report.
> Np 45429 Nvi institution report, log requested year and topLevelOrg

- report-api/src/main/resources/template/nvi.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/CandidateGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/ReportingPeriodGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviCandidate.java
- Following up [PR in NVI](https://github.com/BIBSYSDEV/nva-nvi/pull/268)
- Renamed `reportedPeriod` to `reported` and changed data type to boolean
- Added `ReportingPeriod` with property `year` in test data for candidate
- If candidate is not reported, return "NotReported" as value for `reportedYear` (see nvi sparql query)
> Np 45429 Nvi data report, refactor reporting period

- gradle/libs.versions.toml
- report-api/build.gradle
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchDataReport.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReport.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/service/DatabaseQueryService.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/service/QueryService.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/service/SparqlEndpointQueryService.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/service/SparqlQueryGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchDataReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportTest.java
- Rename `QueryService` to `DatabaseQueryService`.
- Add interface `QueryService`.
- Add `SparqlEndpointQueryService` -> to be used in next PR
- Move sparql template logic to new class `SparqlQueryGenerator`
> SparqlEndpointQueryService

- docs/openapi.yaml
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReport.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/requests/FetchNviInstitutionReportRequest.java
- template.yaml
For `FetchNviInstitutionReportHandler`:
- Change path to: `/report/institution/nvi-approval`
- Make `reportingYear` required query param
> Np 46410 FetchNviInstitutionReportHandler - change path

- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportProxy.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/client/NviInstitutionReportClient.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportHandlerProxyTest.java
- Handle `400`, `404` -> or else throw `BadGatewayException`
> Np 46410 Handle errors in NviInstitutionReportClient

- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportProxy.java
Fix: Use env var (not string) `BACKEND_CLIENT_SECRET_NAME` in `FetchNviInstitutionReportProxy`
> FetchNviInstitutionReportProxy: Fix secret name

- template.yaml
Inspired by @torbjokv's sharings:
- Make managed policies and define explicitly for lambdas. 
- Add policy `SecretsManagerPolicy` for `FetchNviInstitutionReportProxyHandler`
> Make permissions explicit and precise

- report-api/src/main/resources/template/nvi-institution-status.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusHeaders.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestApproval.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestApprovalStatus.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviCandidate.java
Changes according to [Instruks for lesing av NVI-kontrolldata (Excel) for superbrukere](https://www.cristin.no/nvi-rapportering/nvi-veiledninger/hvordan_lese_nvi-kontrolldata.html)
- Rename `RAPPORTERT_STATUS` to `RAPPORTSTATUS`
- Bind values `J`,`N` or `?` to `RAPPORTSTATUS` depending on `globalApprovalStatus`
> Np 46455 Fix RAPPORTSTATUS

- report-api/src/main/resources/template/nvi-institution-status.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/publication/TestLevel.java
Changes according to [Instruks for lesing av NVI-kontrolldata (Excel) for superbrukere](https://www.cristin.no/nvi-rapportering/nvi-veiledninger/hvordan_lese_nvi-kontrolldata.html)
Bind values `1` or `2` to `KVALITETSNIVAKODE` (instead of `LevelOne` or `LevelTwo`)
> Np 46457 Nvi Institution status report, kvalitetsnivakode changes

- report-api/src/main/resources/template/nvi-institution-status.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusTestData.java
Changes according to [Instruks for lesing av NVI-kontrolldata (Excel) for superbrukere](https://www.cristin.no/nvi-rapportering/nvi-veiledninger/hvordan_lese_nvi-kontrolldata.html)
Bind values `J`,`N` or `?` to `STATUS_KONTROLLERT` depending on `approvalStatus`
> Np 46456 Nvi Institution report, status kontrollert changes

- report-api/src/main/resources/template/nvi-institution-status.sparql
- report-api/src/main/resources/template/nvi.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/CandidateGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviCandidate.java
Getting values like `1^^http://www.w3.org/2001/XMLSchema#integer` for `FAKTORTALL_SAMARBEID` and `VEKTINGSTALL` in the result
Bind `internationalCollaborationFactor` and `publicationTypeChannelLevelPoints` as strings
> Remove schema data types from results

- report-api/src/main/resources/template/nvi-institution-status.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusHeaders.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusTestData.java
Added two new headers in report: `ARSTALL` and `ARSTALL_REG`. (See [instruks](https://www.cristin.no/nvi-rapportering/nvi-veiledninger/hvordan_lese_nvi-kontrolldata.html))
- Bind `publicationDate` `year` as `ARSTALL_REG`
- Bind `reportingPeriod` `year` as `ARSTALL`
> Np 46411 Nvi Institution report, add arstall and arstall_reg

- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportProxy.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportHandlerProxyTest.java
Noticed that access right `MANAGE_NVI` belongs to app admin role, which is not correct in this case.
- Updated expected access right in `FetchNviInstitutionReportProxy` to `MANAGE_NVI_CANDIDATES` (Role: `Nvi-Curator`)
> Nvi institution report, update access right to MANAGE_NVI_CANDIDATES

- report-api/src/main/resources/template/nvi-institution-status.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestGlobalApprovalStatus.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviCandidate.java
- Add enum `TestGlobalApprovalStatus`
- Set `RAPPORTSTATUS` in nvi institution report to `"T"` if `globalApprovalStatus` is `Dispute`
> Add global approval status Dispute

- report-api/src/main/resources/template/nvi-institution-status.sparql
- report-api/src/main/resources/template/nvi.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/NviTestUtils.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/ApprovalGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/CreatorAffiliationPointsGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/InstitutionPointsGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestApproval.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestCreatorAffiliationPoints.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestInstitutionPoints.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviCandidate.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviContributor.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestPublicationDetails.java
Instead of calculating points per affiliation with sparql, this is now available in the index data model (See [latest changes](https://github.com/BIBSYSDEV/nva-nvi/pull/289) in nva-nvi repo). This will reduce complexity and optimize query.
- Update model for `InstitutionPoints` and `CreatorAffiliationPoints` in test data
- Update sparql queries
> Np 46529 Refactor nvi points for affiliation

- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/loader/BulkLoadHandlerTest.java
- data-report-commons/build.gradle
- gradle/libs.versions.toml
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportProxy.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/model/ReportRequest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchDataReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviCandidate.java
- Bumping Jena from 4.x to 5.x creates a few issues due to a) transitive dependencies and b) (possibly due to java version — 17 is now required), management of BigDecimal.
As a result:
- Specify Jackson dependency directly
- Don't use apache HTTP values
- Allow trailing zeroes in values
Finally, I have included some literals here. We need to figure out if these are OK (in tests, I think "yes").
> Bump jena > 5.0.0

- bulk-load/build.gradle
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/aws/AwsSqsClient.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/queue/MessageResponse.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/queue/QueueClient.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandler.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandlerTest.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/transformer/FakeSqsClient.java
- gradle/libs.versions.toml
- template.yaml
Bug: NP-46736 BulkTransformer: n-triples are generated twice for all key-batches. Switch from eventbus to sqs-queue
> BulkTransformer, replace event bridge with sqs client

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandler.java
- template.yaml
- Send new event before generating and persisting ntriples. We have configured a DLQ and can re-process failed events with a DLQ redrive.
- `BulkTransformerHandler` needs a longer timeout. Setting to 300 sek, and therefore having to adjust visibility timeout for queue `BulkTransformerQueue`
> BulkTransformerHandler: Process in parallell and timeout config

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/loader/BulkLoadHandler.java
Argument: Lets us debug, resolve and retry loading _only_ for failed files
> BulkLoadHandler, set loader spec failOnError to false

- report-api/src/main/resources/template/nvi-institution-status.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusHeaders.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/ApprovalGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestApproval.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviCandidate.java
- Removed headers that are not in use and not implemented
- Replaced `partOf`-filter with `involvedOrganization`-select to reduce complexity and query time
Next PR: Move data manipulation/transformation from sparql query to java code
> Update nvi model with involvedOrganizations

- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/ApprovalGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/BlankNodeUtil.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/CreatorAffiliationPointsGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/InstitutionPointsGenerator.java
Previously, we weren't creating valid blank nodes, not causing any failure, but the triples we created were ignored and created a lot of noisy log messages when building.
> Create valid blank nodes uniformly

- bulk-export/src/main/java/no/sikt/nva/data/report/api/export/CsvTransformer.java
- bulk-export/src/main/java/no/sikt/nva/data/report/api/export/DocumentType.java
- bulk-export/src/main/resources/template/nvi.sparql
- bulk-export/src/test/java/no/sikt/nva/data/report/api/export/CsvTransformerTest.java
- bulk-export/src/test/java/no/sikt/nva/data/report/api/export/NviIndexDocument.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/NquadsTransformer.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/transformer/NquadsTransformerTest.java
- data-report-commons/src/main/java/commons/formatter/CsvFormatter.java
- data-report-commons/src/main/java/commons/handlers/BulkTransformerHandler.java
- data-report-commons/src/main/java/commons/model/ReportType.java
- data-report-commons/src/test/java/commons/formatter/CsvFormatterTest.java
- data-report-commons/src/test/java/commons/model/ReportTypeTest.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/TestData.java
Jira task: NP-46747 Database-dumps for initial import
Part three:
- For each key batch in `location` (/folder) _nvi_, `CsvBulkTransformer` creates csv file for nvi data and persists in folder `/nvi` in s3 bucket _data-report-csv-export_
- Also, fixed a bug in `BulkTransformerHandler`. Previously, the handler received `location` as input, but did not actually fetch the key batch from that given location. Added `location` as prefix when fetching single batch in `BulkTransformerHandler`.
> Np 47307 CsvTransformer, create files for nvi data

- template.yaml
DataLoadingHandler (SingleObjectDataLoader) does not need to be in VPC, since it is not loading data to Neptune anymore
> DataLoadingHandler, remove VPC config

- bulk-export/src/main/java/no/sikt/nva/data/report/api/export/CsvTransformer.java
- bulk-export/src/test/java/no/sikt/nva/data/report/api/export/CsvTransformerTest.java
- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoader.java
- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoaderTest.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/TestData.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/model/IndexDocument.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/model/NviIndexDocument.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/model/PublicationIndexDocument.java
Jira task: NP-47381 Generate csv-files on s3 for new and changed publications and nvi candidates
Part two:
- `SingleObjectDataLoader`, generate five csv-files ("affiliation", "contributor", "funding", "identifier", "publication") when receiving s3 events for new and changed publications
- File path contructed with following pattern: {reportType}/{identifier}-{timestamp}. Example: publication/865ea1eb-3fab-421e-8517-936672c8d8d1-2024-08-21T11:31:54.032116
Next PR:
- Log failures and DLQ for retries
> Np 47403 SingleObjectDataLoader, generate publication reports

- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/PersistedResourceCsvTransformer.java
- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/PersistedResourceCsvTransformerTest.java
- template.yaml
Changes:
- Rename `SingleObjectDataLoader` to `PersistedResourceCsvTransformer`
- Changed target for `PersistedResourcesEventRule`, now targeting `TransformPersistedResourceQueue` (which `PersistedResourceCsvTransformer` consumes messages from). In this way, if `PersistedResourceCsvTransformer` fails, messages are sent to DLQ, and can be moved to `TransformPersistedResourceQueue` for a retry (with a DLQ _redrive_)
> Np 47403 PersistedResourcesEventRule, TransformPersistedResourceQueue

- template.yaml
Step 3 in [Create a storage credential for connecting to AWS S3](https://docs.databricks.com/en/connect/unity-catalog/storage-credentials.html#create-a-storage-credential-for-connecting-to-aws-s3)
Change:
- Make the trust relationship policy self-assuming
> DataWarehouseRole: Make self-assuming

- data-report-commons/src/main/java/commons/formatter/CsvFormatter.java
- data-report-commons/src/test/java/commons/formatter/CsvFormatterTest.java
Jira task: NP-47696 All reports: quote all special strings
Data plattform struggling to consume publications with titles like _The Athletics Injury Prevention Programme Can\r\nHelp to Reduce the Occurrence at Short Term of\r\nParticipation Restriction Injury Complaints in\r\nAthletics: A Prospective Cohort Study_
Our data should be washed properly, but if this is not the case, these strings should be quoted during export.
Quote mode `MINIMAL`: Quotes fields which contain special characters such as a the field delimiter, quote character or any of the characters in the line separator string.
> CsvFormatter: Quote mode minimal

- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/PersistedResourceCsvTransformerTest.java
- data-report-commons/src/main/resources/template/identifier.sparql
- documentation/identifierReport.md
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/PublicationHeaders.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/SampleData.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/publication/SampleAdditionalIdentifier.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/publication/SamplePublication.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/model/PublicationIndexDocument.java
Update identifier report:
- Add additional identifiers
- Remove fundings, these are exported via [funding report](https://github.com/BIBSYSDEV/nva-data-report-api/blob/main/documentation/fundingReport.md)
@ketilaa: @torbjokv mentioned that the "main handle" not necessarily is available in additionalIdentifiers, but on the publication root level. Do you know if this is relevant for data export? Should we exclude `additionalIdentifiers` with `type` `HandleIdentifier` to avoid confusion?
> Np 47673 Identifier report: Additional identifiers

- data-report-commons/build.gradle
- data-report-commons/src/main/java/commons/formatter/CsvFormatter.java
- data-report-commons/src/test/java/commons/formatter/CsvFormatterTest.java
Even though string containing special characters are quoted, data warehouse is still not able to consume strings with line seperators. Example: _" \r\nVernehelgener mot pest i Norge i senmiddelalderen"_ (https://dev.nva.sikt.no/registration/019055152ee5-e32d4020-ece8-4afd-a42c-791a2b2c9a31)
Using [org.apache.commons.text](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/package-summary.html) `StringEscapeUtils` `escapeJava()`-method and `CSVFormat.setEscape('\\') `to escape these.
`StringEscapeUtils.escapeJava()`:
Escapes the characters in a String using Java String rules. Deals correctly with quotes and control-chars (tab, backslash, cr, ff, etc.)
Example:
input string: `He didn't say, "Stop!"`
output string: `He didn't say, \"Stop!\"`
> All reports: Escape line seperators
