- data-loading/build.gradle
- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoader.java
- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoaderTest.java
Log root folder of event object
> Np 45918 Differentiate object folders

- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoaderTest.java
- data-report-commons/build.gradle
- data-report-commons/src/main/java/commons/db/GraphStoreProtocolConnection.java
- data-report-commons/src/test/java/commons/db/GraphStoreProtocolConnectionTest.java
- Moves server init so it is running before it is used
- Adds some code to allow querying to check the response of a write (this hopefully won't survive for long)
- Fixes a few tests
- Removes dead code
> Np 45985 fix on top of wip code

- data-report-commons/src/main/java/commons/db/GraphStoreProtocolConnection.java
- data-report-commons/src/test/java/commons/db/GraphStoreProtocolConnectionTest.java
> Add delete method

- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoaderTest.java
- data-report-commons/src/test/java/commons/db/GraphStoreProtocolConnectionTest.java
- Echoing production environment
- initialise database once
- clear database between tests
- stop database after tests have run
> Initialize test database once

- template.yaml
- S3GatewayEndpoint
- PrivateRouteTableLambdaAssociation
- Modified LambdaSecurityGroup to allow all outbound traffic, might want to narrow this down to only allow outbound traffic to S3.
> Fix s3 connection

- data-loading/build.gradle
- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoader.java
- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/utils/BasePath.java
- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoaderTest.java
- data-report-commons/src/main/java/commons/db/utils/GraphName.java
- data-report-commons/src/test/java/commons/db/utils/GraphNameTest.java
- Use API_HOST
- Fix tests to match this
> Use api-host as base path

- data-report-commons/src/main/java/commons/db/GraphStoreProtocolConnection.java
- I guess we shouldn't swallow unchecked exceptions
> Rethrow RT-exceptions

- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoaderTest.java
- data-report-commons/src/main/java/commons/db/GraphStoreProtocolConnection.java
- data-report-commons/src/test/java/commons/db/GraphStoreProtocolConnectionTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchDataReportTest.java
- template.yaml
> Add sparql endpoint

- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoader.java
- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/service/GraphService.java
- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoaderTest.java
- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/testutils/model/nvi/IndexDocument.java
- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/testutils/model/nvi/IndexDocumentWithConsumptionAttributes.java
- data-report-commons/src/main/java/commons/db/GraphStoreProtocolConnection.java
Jira task: [Update existing data](https://unit.atlassian.net/browse/NP-45986)
> NP-45986 Dataloader: Update existing data

- data-report-commons/src/main/java/commons/db/GraphStoreProtocolConnection.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchDataReportTest.java
> Use transactional query

- report-api/src/main/resources/template/publication.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/Constants.java
- Add `year` as last path element in pulicationChannel uris
- Adjust sparql to bind pulicationChannel identifier as channelId
> Fix publicationChannel identifier sparql

- docs/openapi.yaml
- template.yaml
Allow external client with scope reporting-read to use endpoints.
> Add scope reporting-read. Add ExternalCognitoAuthorizerArn.

- report-api/src/main/resources/template/nvi.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/TestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviOrganization.java
Update nvi sparql, also selecting top level affiliations
> Update nvi sparql, also selecting top level affiliations

- data-loading/src/main/resources/nvi_context.jsonld
Define partOf as container with ids in nvi context
> Nvi context, add partOf

- bulk-load/build.gradle
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/GenerateKeyBatchesHandler.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/KeyBatchRequestEvent.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/Nquads.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/NquadsTest.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/transformer/GenerateKeyBatchesHandlerTest.java
- gradle/libs.versions.toml
- template.yaml
- Adds the key based batch handler from search api
- next step add transformation code
> Add key based batch handler

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/GenerateKeyBatchesHandler.java
- template.yaml
- Simply adds the bucket folder to the key, which means that we can find the json
> Add support for resources and nvi candidates

- database-tools/src/main/java/no/sikt/nva/data/report/dbtools/DatabaseResetHandler.java
Log response body if not successful
> Log response body if not successful

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandler.java
- template.yaml
- Adds default constructors
- Adds template referring to above
> Add AWS glue

- report-api/src/main/resources/template/nvi.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchDataReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/formatter/ResultUtils.java
- Tests that verify that all report types support `offset` and `pageSize`
- Add offset to nvi query
> Fix nvi offset

- bulk-load/src/test/resources/publication.json
- report-api/src/main/resources/template/affiliation.sparql
- report-api/src/main/resources/template/contributor.sparql
- report-api/src/main/resources/template/funding.sparql
- report-api/src/main/resources/template/identifier.sparql
- report-api/src/main/resources/template/publication.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/formatter/ResultUtils.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/TestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/publication/PublicationGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/publication/TestPublication.java
- Adds publication status to every relevant response (i.e. not NVI)
- Some linting
> Add publication status

- report-api/src/main/resources/template/nvi.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/TestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/model/nvi/CandidateGenerator.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/nvi/TestNviCandidate.java
Adds nvi candidate applicable status to nvi response
> Add nvi applicable

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandler.java
Fix bucket name for expanded resources bucket in BulkTransformerHandler
> Fix bucket name for expanded resources bucket in BulkTransformerHandler

- template.yaml
- Allow lambdas to send and receive event bridge events
> Add EventBridgeVPCEndpoint

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandler.java
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/GenerateKeyBatchesHandler.java
`S3Driver.defaultS3Client` uses `ApacheHttpClient` with timeout config etc.
> Use default s3 client from nva commons

- template.yaml
Define vpc config explicitly for relevant lambdas
> Define vpc config explicitly for relevant lambdas

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/GenerateKeyBatchesHandler.java
- The "folder" isn't a folder, it is a "CommonPrefix", which we need to remove
> Filter common prefixes from keys list

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/GenerateKeyBatchesHandler.java
- Call to non-existent value in logging caused the issue
- Moved logic to emit event based on presence of next key, logging thereafter
> Invoke emit event conditionally

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/GenerateKeyBatchesHandler.java
- Since we never know if the keys are present, optionalize them
> Linearize process with optional

- bulk-load/build.gradle
- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandler.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandlerTest.java
- data-loading/build.gradle
- gradle/libs.versions.toml
- report-api/build.gradle
- Bump commons to allow check of successful putObject
- Remove a few stray toml deps
- Delete consumed batches
> Delete consumed batches

- README.md
With Pre-run steps, Run bulk upload steps and Post-run steps
> Add How to run a bulk upload in readMe

- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchDataReport.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/model/ReportFormat.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/model/ReportRequest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchDataReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/formatter/ResultUtils.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/model/ReportFormatTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/ValidRequestSource.java
For now just returning csv when excel is requested, adding excel support in next PR
> Np 46190 ReportFormat excel

- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchDataReport.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/model/ReportFormat.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchDataReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/formatter/ResultSorter.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/ValidExcelRequestSource.java
- template.yaml
- Add OOXML_SHEET as supported media type for ReportFormat excel
- Add application/vnd.openxmlformats-officedocument.spreadsheetml.sheet as supported BinaryMediaTypes for api
> Np 46190 support xlsx

- docs/openapi.yaml
- gradle/libs.versions.toml
- report-api/build.gradle
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReport.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportTest.java
Returns `401 Unauthorized` if user does not have access right `MANAGE_NVI`
> Fetch nvi institution report access rights

- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReport.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/model/ReportType.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/service/QueryService.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchDataReportTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/ValidRequestSource.java
Distinguishing nvi institution status report from the other data reports since this has different input and response
> Remove nvi-institution-status as data report type

- template.yaml
Necessary for validating access rights
> Add env var COGNITO_HOST for FetchNviInstitutionReportHandler

- template.yaml
`FetchNviInstitutionReportHandler` is timing out when attempting to fetch user info from Cognito. Adding vpc endpoint as attempt of fixing this.
> Add CognitoVpcEndpoint

- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoaderTest.java
- docs/openapi.yaml
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportProxy.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportHandlerProxyTest.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/requests/FetchNviInstitutionReportProxyRequest.java
- template.yaml
- Validate access rights
- Extract and log requesting users top level org
> Np 46410  FetchNviInstitutionReportProxyHandler

- template.yaml
While i figure out https://github.com/BIBSYSDEV/nva-data-report-api/pull/102
> Add readSecret policy for secret manager

- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/FetchNviInstitutionReportProxy.java
- report-api/src/main/java/no/sikt/nva/data/report/api/fetch/client/NviInstitutionReportClient.java
Refactor: Encode input stream to string in handler, not client
> Refactor: Encode input stream to string in handler, not client

- report-api/src/main/resources/template/nvi-institution-status.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviTestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/TestData.java
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/publication/TestPublication.java
Bind values to headers: `ETTERNAVN` and `FORNAVN`
> Np 46444 Nvi Institution report, add contributor name

- report-api/src/main/resources/template/nvi-institution-status.sparql
- report-api/src/test/java/no/sikt/nva/data/report/api/fetch/testutils/generator/NviInstitutionStatusTestData.java
Calculate points for affiliation and bind value to `FORFATTERVEKT`
> Np 46445 Nvi Institution report, add FORFATTERVEKT

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandler.java
- data-loading/build.gradle
- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/SingleObjectDataLoader.java
- data-report-commons/build.gradle
- data-report-commons/src/main/java/commons/db/utils/DocumentUnwrapper.java
- data-report-commons/src/main/resources/nvi_context.jsonld
- data-report-commons/src/test/java/commons/db/utils/DocumentUnwrapperTest.java
- report-api/build.gradle
Updated nvi context.
Long term solution: Use remote context
> Update local nvi context

- report-api/src/main/resources/template/affiliation.sparql
- report-api/src/main/resources/template/contributor.sparql
- report-api/src/main/resources/template/funding.sparql
- report-api/src/main/resources/template/identifier.sparql
- report-api/src/main/resources/template/nvi-institution-status.sparql
- report-api/src/main/resources/template/nvi.sparql
- report-api/src/main/resources/template/publication.sparql
- Filters allow the query to discard the query exec early
> Move filters for early execution

- template.yaml
Jira task: NP-46353 DLQs for tail-lambdas
> Add GenerateKeyBatchesDLQ

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandler.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandlerTest.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/transformer/NquadsTest.java
Replace null characters in transformer with empty string
> Np 46853 Replace null chars

- template.yaml
Alarm in lsack if number of messages in GenerateNviInstitutionReportDLQ > 1
> Add NviInstitutionReportDLQAlarm

- docs/openapi.yaml
Supported formats seems to be:
CSV(List.of(TEXT_CSV)),
TEXT(List.of(TEXT_PLAIN)),
EXCEL(List.of(MICROSOFT_EXCEL, OOXML_SHEET));
> remove ducumented json ld response that is not implemented

- bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandler.java
- bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandlerTest.java
Whole bulk transformation failing if one object key is not found in bucket _persisted-resources_. Reasons for this could be other activities in the system between key-batch generation and bulk transformation.
To fix this: Just log object keys that are not found.
> BulkTransformer, do not fail when object key not found

- bulk-export/src/main/java/no/sikt/nva/data/report/api/export/CsvTransformer.java
- bulk-export/src/test/java/no/sikt/nva/data/report/api/export/CsvTransformerTest.java
`CsvTransformer`: Add csv file extension to export files
> CsvTransformer: Add csv file extension to export files

- data-report-commons/src/main/resources/template/affiliation.sparql
- data-report-commons/src/main/resources/template/contributor.sparql
- data-report-commons/src/main/resources/template/funding.sparql
- data-report-commons/src/main/resources/template/identifier.sparql
- data-report-commons/src/main/resources/template/nvi.sparql
- data-report-commons/src/main/resources/template/publication.sparql
- report-api/src/main/resources/template/affiliation.sparql
- report-api/src/main/resources/template/contributor.sparql
- report-api/src/main/resources/template/funding.sparql
- report-api/src/main/resources/template/identifier.sparql
- report-api/src/main/resources/template/nvi.sparql
- report-api/src/main/resources/template/publication.sparql
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/NviTestData.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/PublicationHeaders.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/TestData.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/nvi/TestNviCandidate.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/publication/TestPublication.java
Jira task: NP-47408 Add modifiedDate to all csv reports
> Np 47408 Add modifiedDate to all reports

- template.yaml
Removed Neptune and Neptune related config in template
Next steps in cleanup:
- Remove unused handlers from template
- Remove unused handlers from code
> Remove Neptune and VPC from template

- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/PersistedResourceCsvTransformer.java
- data-loading/src/main/java/no/sikt/nva/data/report/api/etl/model/PersistedResourceEvent.java
- data-loading/src/test/java/no/sikt/nva/data/report/api/etl/PersistedResourceCsvTransformerTest.java
- template.yaml
What should have been a part of https://github.com/BIBSYSDEV/nva-data-report-api/pull/164
> Fix eventbridge rule, add sqs policy

- data-report-commons/src/main/resources/template/publication.sparql
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/SampleData.java
NP-47674 Publication report: channelType value should not include NVA namespace
> Publication report: Remove channelType namespace

- data-report-commons/src/main/resources/template/identifier.sparql
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/SampleData.java
- testing-utils/src/main/java/no/sikt/nva/data/report/testing/utils/generator/publication/SamplePublication.java
Fix HandleIdentifier filter
- filter additional identifiers with type `HandleIdentifier` comparing string value without namespace
> Fix HandleIdentifier filter

- documentation/affiliationReport.md
- documentation/contributorReport.md
- documentation/fundingReport.md
- documentation/identifierReport.md
- documentation/nviReport.md
- documentation/publicationReport.md
Requested by analyseplattformen
> Document unique identifiers for all reports

- template.yaml
Ticket: https://sikt.atlassian.net/browse/NP-49069
Enables backup of export bucket.
> [np-49069] feat: Enable backup of S3 bucket
